### ISSUE TITLE
Code coverage in kelinci

### ISSUE THREAD

**Issue by vidhya-kv** [isstac/kelinci#4]
It is possible to measure code coverage using afl. is the same also possible with the kelinci tool?
I would like to do deterministic fuzzing based on the results of code coverage that the tool returns

Any inputs would help

**Comment by rodykersten** [comment]
Kelinci adds similar instrumentation as AFL, measuring an approximation of branch coverage.

**Comment by vidhya-kv** [comment]
How do i use options like tmin etc to optimise the test paths to achieve better coverage. I am trying with a demo piece of code but unable to get proper code coverage improvement

**Comment by rodykersten** [comment]
I have not tested with afl-tmin, but in theory it should work as usual. Note though that Kelinci is much, much slower than normal AFL, so don't expect the same or similar performance.

As a side node, afl-tmin does not improve coverage. It minimizes the test suite while maintaining the level of coverage.
